language: python
sudo: required
dist: xenial
python: "3.7.0"
cache: 
  pip: true
install:
  - pip install -r requirements_dev.txt
  - make install 
script:
  - make lint
  - make tests
after_success:
  - codecov --file coverage.xml